### ISSUE TITLE
PHP Error after Docker contrainer start.

### ISSUE THREAD

**Issue by Jordessey** [alextselegidis/easyappointments-docker#16]
Hi There, I know i'm probably being dumb but I created an instance with the following docker compose file (secrets obscured). The container is published behind Traefik reverse web proxy.
```
services:

  easyapointments:
    image: alextselegidis/easyappointments:latest
    restart: always
    networks:
      - traefik_network
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.easyappointments.rule=Host(`careers.mydomain.school.nz`)"
      - "traefik.http.routers.easyappointments.entrypoints=websecure"
      - "traefik.http.services.easyappointments.loadbalancer.server.port=80"
      - "traefik.http.routers.easyappointments.service=easyappointments"
      - "traefik.http.routers.easyappointments.tls.certresolver=letsencrypt"
    ports:
      - '85:80'
    environment:
      - BASE_URL=https://career.rangiorahigh.school.nz
      - DEBUG_MODE=TRUE
      - DB_HOST=mysql
      - DB_NAME=easyappointments
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - easyappointments:/var/www/html

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointments
    volumes:
      - mysql:/var/lib/mysql

volumes:
  easyappointments:
  mysql:

networks:
  traefik_network:
    external: true
```

when I start the container, I load a webpage but am greeted with the following PHP errors.

![Image](https://github.com/user-attachments/assets/8b78ae1c-eae4-4b22-b746-b4bcb09da30e)

If i drop it down the the following docker compose file (host port 85 as host port 80 is in use by Traefik).

```
services:

  easyapointments:
    image: alextselegidis/easyappointments:latest
    restart: always
    ports:
      - '85:80'
    environment:
      - BASE_URL=http://localhost
      - DEBUG_MODE=TRUE
      - DB_HOST=mysql
      - DB_NAME=easyappointments
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - easyappointments:/var/www/html

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointments
    volumes:
      - mysql:/var/lib/mysql

volumes:
  easyappointments:
  mysql:
```

![Image](https://github.com/user-attachments/assets/4d9e26f4-fcd2-49e5-a264-e638fe7ef3e3)

(Edit, Setup error went away overnight)

Is there some configuration I am missing to publish Easyappointments through traefik?
Sorry if im being dumb
