### ISSUE TITLE
Docker Pull MySQL failed on RPI

### ISSUE THREAD

**Issue by JiroMusik** [alextselegidis/easyappointments-docker#2]
HI there,
I was just trying to use the docker-compose file in Portainer Stacks to Deploy the two containers via Portainer.
Unfortunately, it stops while pulling the mySQL 5.7 image, maybe not available on Raspberry?
I am not sure how I could go forward with installation, choose newer SQL or what is the way to go?

Thanks in advance

**Comment by JiroMusik** [comment]
WIth mariadb I got this working, but the App container fails with:
exec /sbin/tini: exec format error

**Comment by alextselegidis** [comment]
Hello! 

Which docker config did you use? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by JiroMusik** [comment]
Hi, I tried with the config from this repository and then with these:

```
version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=easyappointments
      - MYSQL_USER=easyappointments
      - MYSQL_PASSWORD=easyappointments
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./easy-appointments-data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - easyappointments-network
    restart: always

  application:
    image: jamrizzi/easyappointments
    volumes:
      - ./easy-appointments:/app/www
    depends_on:
      - db
    ports:
      - 8089:8888
    environment:
      - DB_HOST=db
      - DB_USERNAME=easyappointments
      - DB_NAME=easyappointments
      - DB_PASSWORD=easyappointments
      - TZ=Europe/Berlin
      - BASE_URL=http://192.168.75.33:8089 
    networks:
      - easyappointments-network
    restart: always

networks:
  easyappointments-network:
```

other version, same error

```

version: "2"
services:
  easyappointments-data:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: easyappointments
      MYSQL_ROOT_PASSWORD: hellodocker

  easyappointments:
    image: jamrizzi/easyappointments:latest
    environment:
      DB_NAME: easyappointments
      DB_PASSWORD: hellodocker
      BASE_URL: http://localhost:8888
    ports:
      - 8888:8888
    links:
      - easyappointments-data:db
```
