### ISSUE TITLE
Problem with sending E-Mails out of the Box

### ISSUE THREAD

**Issue by sjerocom** [alextselegidis/easyappointments-docker#22]
Hello, the docker deployment works really fine, but i cant get the mail send to working.... i created the enviroment files as described, but i cant get the application to send an email

i logged into the container and tried to send an mail with a small script and msmtp => works - tried to replace ssmtp with msmtp but i failed and cant get it to work

is there any chance to get a ui interface in settings to set up the smtp mail send? 
or any support, how i could get it to run out of the box?

yes the credentials and everything is working, from different containers and also from the very same container with a testscript!

**Comment by chris2deuce** [comment]
Could you please check if #14 and my comment there regaring the protocol to use, will fix your problem?

**Comment by sjerocom** [comment]
i tried every variant, ssl, mail, html, text, tsl, ssl and so on - i also tried to replace the ssmtp to msmtp (php-senmail.ini changed) => what i noticed, with my testscript, i can send mails without any problem - but i can't get it to work with the on board Email_configuration 

here ist the email.php from the config folder (my last non working try):

```
<?php defined('BASEPATH') or exit('No direct script access allowed');

$config['useragent'] = 'Easy!Appointments';
$config['protocol'] = 'mail'; // or 'smtp'
$config['mailtype'] = 'html'; // or 'text'
$config['smtp_debug'] = '0'; // or '1'
$config['smtp_auth'] = TRUE; //or FALSE for anonymous relay.
$config['smtp_host'] = 'smtp.strato.de';
$config['smtp_user'] = 'xxx@teichzeit.at';
$config['smtp_pass'] = 'xxx';
$config['smtp_crypto'] = 'tls'; // or 'tls'
$config['smtp_port'] = 587;
$config['from_name'] = 'Teichzeit.at - Buchungssystem';
$config['from_address'] = 'xxx@teichzeit.at';
$config['reply_to'] = 'xxx@teichzeit.at';
$config['crlf'] = "\r\n";
$config['newline'] = "\r\n";
```

i dont know if #14 ist the same problem ... to be honest, i got lost in changing and get it to work :(
i dont understand, why this is happening or whats this causing, becaus i use from many different containers/setups an smtp and everything worked instantly, except this one :(

what do you need from my setup - i didnt get any errormessage in the gui, i simply doesnt get anywhere an error or log :(

**Comment by sjerocom** [comment]
well i installed msmtp, configured in /root/.msmtprc an default account => sendmail over CLI works
i created a php-sendmail.ini with reverence to the msmtp mail tool

if i try to send a mail over the booking site, i get as response:

172.18.0.* - - [05/Apr/2025:07:38:39 +0000] "POST /index.php/booking/get_available_hours HTTP/1.1" 200 850 "https://buchung.teichzeit.at/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
msmtp: account default not found: no configuration file available

i also created an msmtp log file, but the request from the app is never seen the log?! 

everythings works like a charm, except the mails - and i cant find more logs :(

**Comment by sjerocom** [comment]
also, here is my docker-compose.yml:

```
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  easyappointments:
    container_name: buchung_teichzeit_xxx
    image: alextselegidis/easyappointments:latest
    restart: always
    networks:
      - proxy
      - buchung_teichzeit_xxx_network
    environment:
      - BASE_URL=${BASE_URL}
      - DEBUG_MODE=${DEBUG_MODE}
      - DB_HOST=buchung_teichzeit_xxx_mysql
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTH=${SMTP_AUTH}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_REPLY_TO_ADDRESS=${SMTP_REPLY_TO_ADDRESS}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_TLS=${SMTP_CRYPTO}
      - SMTP_DEBUG=4
      - CRLF="\r\n"
      - NEWLINE="\r\n"
    volumes:
      - buchung_teichzeit_xxx:/var/www/html
      - ./configs/php-sendmail.ini:/usr/local/etc/php/conf.d/php-sendmail.ini
      - ./configs/msmtprc:/root/.msmtprc

  mysql:
    container_name: buchung_teichzeit_xxx_mysql
    image: mysql:8.0
    restart: always
    networks:
      - proxy
      - buchung_teichzeit_xxx_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - buchung_teichzeit_xxx_mysql:/var/lib/mysql
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql


  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-buchung_teichzeit_xxx
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ../beszel/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel_buchung_teichzeit_xxx.sock
      KEY: 'xxx'

volumes:
  buchung_teichzeit_xxx:
  buchung_teichzeit_xxx_mysql:

networks:
  proxy:
    external: true
    name: proxy
  buchung_teichzeit_xxx_network:
    driver: bridge
```

and my .env (anonym :)):
```
# Allg. Einstellungen
BASE_URL=https://xxx
DEBUG_MODE=true

# MySQL Einstellungen
MYSQL_ROOT_PASSWORD=xxx
MYSQL_DATABASE=buchung_teichzeit_xxx_mysql
MYSQL_USER=buchung_teichzeit_xxx_mysql
MYSQL_PASSWORD="xxx"

# SMTP Einstellungen
SMTP_HOST=smtp.strato.de
SMTP_PORT=587
SMTP_AUTH=TRUE
SMTP_PROTOCOL=smtp
SMTP_USERNAME=xxx
SMTP_PASSWORD="xxx"
SMTP_FROM_ADDRESS=xxx
SMTP_FROM_NAME="Teichzeit.at - Buchungssystem"
SMTP_REPLY_TO_ADDRESS=xxx
SMTP_CRYPTO=tls
SMTP_TLS=YES
```

my configs/php-sendmail.ini:

`sendmail_path = "/usr/bin/msmtp -t"`

my msmtprx file:

```
account default
host smtp.strato.de
port 587
from xxx
user xxx
password xxx
auth on
tls on
logfile ~/.msmtp.log
```

my init.sql (to create an privilege the user for the DB):

```
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE USER 'buchung_teichzeit_xxx_mysql'@'%' IDENTIFIED BY 'xxx';
GRANT ALL PRIVILEGES ON buchung_teichzeit_xxx.* TO 'buchung_teichzeit_xxx_mysql'@'%';
FLUSH PRIVILEGES;
```

and my Dockerfile:

```
# Verwende das ursprüngliche EasyAppointments-Image als Basis
FROM alextselegidis/easyappointments:latest

# Aktualisiere die Paketliste und installiere msmtp und andere benötigte Pakete
RUN apt-get update && apt-get install -y \
    msmtp \
    && rm -rf /var/lib/apt/lists/*  # Entferne unnötige Dateien, um das Image klein zu halten

# Kopiere deine benutzerdefinierte Konfiguration (z. B. msmtprc und php-sendmail.ini)
COPY ./configs/php-sendmail.ini /usr/local/etc/php/conf.d/php-sendmail.ini
COPY ./configs/msmtprc /root/.msmtprc

# Setze den richtigen Sendmail-Pfad für PHP
RUN echo 'sendmail_path = "/usr/bin/msmtp -t"' >> /usr/local/etc/php/conf.d/php-sendmail.ini

# Weiterer Konfigurationsbedarf
```
